### PR TITLE
Added ICRA 2024 bib to the references.bib file

### PR DESCRIPTION
**Pull request by watakandai**

### CODE REVIEW

**Comment by jmskov** [comment]
Did you edit other refs or work off an old branch? There are some changes to other refs I didn't expect.

**Comment by watakandai** [comment]
ah good catch. It's my editor's linter deleting the unnecessary spaces at the end. I should ignore them.

**Comment by watakandai** [comment]
I pulled the most recent branch and worked from there. ...

**Comment by jmskov** [comment]
Looks good, thanks for the changes.

**Pull request merged**
