### PR TITLE
Updated RSS publication with PDF url

### PR DESCRIPTION
**Pull request by MuvvalaKaran**

### CODE REVIEW

**Comment by Jmcjack** [comment]
Check my comment on the file. Please fix.

**Comment by Jmcjack** [comment]
bump

**Comment by MuvvalaKaran** [comment]
I will fix it and create a PR tomorrow

**Comment by Jmcjack** [comment]
bump 😊

**Comment by MuvvalaKaran** [comment]
Thanks for the reminder. Check the new URL. Let me know if you see any problem.

**Comment by Jmcjack** [comment]
See fix, still need the comma

**Comment by MuvvalaKaran** [comment]
Thanks. Added comma and created a new commit. FYI, I can not see your original comment on my pdf for some reason.

**Pull request merged**
